openapi: 3.0.0

info:
  title: "授業情報API"
  version: 1.0.0

servers:
  - url: https://hogehoge.example.com/v1/

# 学年クラス曜日を指定して時間割を受け取る
paths:
  "/classes/{class}/{dayOfWeek}":
    get:
      summary: "曜日を指定して1日の時間割を受け取る"
      parameters:
        - name: "class"
          in: path
          type: integer
        - name: "dayOfWeek"
          in: path
          type: string
      responses:
        200:
          description: 成功時のレスポンス
          schema:
            type: object
            properties:
              id:
                type: "integer"
                format: "int64"
                example: 1
              name:
                type: "string"
                example: "論理回路ii"
        404:
          description: 失敗時のレスポンス
          schema:
            type: object
            properties:
              id:
                type: "integer"
                format: "int64"
                example: 404
              name:
                type: "string"
                example: "失敗"
    # /classes/{class}/{dayOfWeek}/{time}
    # get:
    #   summary: "曜日と時間を指定してその時間の科目を受け取る"
  # /classes/{class}/{dayOfWeek}

# patchで学期ごとに時間割を更新?

components:
  schemas:
